version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:cached
    ports:
      - "9003:9003" # For Xdebug
    tty: true # Keeps the container running
