dev:
	docker-compose up
run:
	docker compose -f docker-compose-run.yml up --build
test1:
	vendor/bin/phpunit ./tests/PartOne.php
test2:
	vendor/bin/phpunit ./tests/PartTwo.php
solve:
	php ./src/index.php